name: exc_sim
channels:
  - conda-forge
dependencies:
  - ca-certificates=2025.4.26
  - libcxx=20.1.5
  - libffi=3.3
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libsqlite=3.46.0
  - libzlib=1.2.13
  - ncurses=6.5
  - openssl=1.1.1w
  - pip=25.1.1
  - python=3.9.0
  - readline=8.2
  - setuptools=80.8.0
  - sqlite=3.46.0
  - tk=8.6.13
  - tzdata=2025b
  - wheel=0.45.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zlib=1.2.13
  - pip:
      - contourpy==1.3.0
      - customtkinter==5.2.2
      - cycler==0.12.1
      - darkdetect==0.8.0
      - fonttools==4.58.1
      - importlib-resources==6.5.2
      - kiwisolver==1.4.7
      - llvmlite==0.43.0
      - matplotlib==3.9.4
      - numba==0.60.0
      - numpy==2.0.2
      - packaging==25.0
      - pillow==11.2.1
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - six==1.17.0
      - zipp==3.22.0
